export const storeProducts = [
    {
        id: 1,
        title: "Google Pixel - Black",
        img: "img/google.jpg",
        price: 250,
        company: "GOOGLE",
        info: "O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão. O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500, quando uma misturou os caracteres de um texto para criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas também o salto para a tipografia electrónica, mantendo-se essencialmente inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente com os programas de publicação como o Aldus PageMaker que incluem versões do Lorem Ipsum.",
        inCart: false,
        count: 0,
        total: 0,
    },

    {
        id: 2,
        title: "Samsung S7 edge",
        img: "img/s7.jpg",
        price: 250,
        company: "SAMSUNG",
        info: "O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão. O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500, quando uma misturou os caracteres de um texto para criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas também o salto para a tipografia electrónica, mantendo-se essencialmente inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente com os programas de publicação como o Aldus PageMaker que incluem versões do Lorem Ipsum.",
        inCart: false,
        count: 0,
        total: 0,
    },

    {
        id: 3,
        title: "Tecno Camon 12",
        img: "img/tecno-c12.jpg",
        price: 150,
        company: "TECNO",
        info: "O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão. O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500, quando uma misturou os caracteres de um texto para criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas também o salto para a tipografia electrónica, mantendo-se essencialmente inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente com os programas de publicação como o Aldus PageMaker que incluem versões do Lorem Ipsum.",
        inCart: false,
        count: 0,
        total: 0,
    },

    {
        id: 4,
        title: "Iphone 11",
        img: "img/iphone11.png",
        price: 400,
        company: "APPLE",
        info: "O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão. O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500, quando uma misturou os caracteres de um texto para criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas também o salto para a tipografia electrónica, mantendo-se essencialmente inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente com os programas de publicação como o Aldus PageMaker que incluem versões do Lorem Ipsum.",
        inCart: false,
        count: 0,
        total: 0,
    },

    {
        id: 5,
        title: "Iphone X",
        img: "img/iphoneX.jpg",
        price: 280,
        company: "APPLE",
        info: "jfkfbvobvb",
        inCart: false,
        count: 0,
        total: 0,
    },

    {
        id: 6,
        title: "Samsung S8",
        img: "img/s8.jpg",
        price: 330,
        company: "SAMSUNG",
        info: "O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão. O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500, quando uma misturou os caracteres de um texto para criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas também o salto para a tipografia electrónica, mantendo-se essencialmente inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente com os programas de publicação como o Aldus PageMaker que incluem versões do Lorem Ipsum.",
        inCart: false,
        count: 0,
        total: 0,
    },

    {
        id: 7,
        title: "Samsung S9",
        img: "img/s9.jpg",
        price: 380,
        company: "SAMSUNG",
        info: "O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão. O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500, quando uma misturou os caracteres de um texto para criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas também o salto para a tipografia electrónica, mantendo-se essencialmente inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente com os programas de publicação como o Aldus PageMaker que incluem versões do Lorem Ipsum.",
        inCart: false,
        count: 0,
        total: 0,
    },

    {
        id: 8,
        title: "Hp G640",
        img: "img/hp.jpg",
        price: 130,
        company: "HP",
        info: "O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão. O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500, quando uma misturou os caracteres de um texto para criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas também o salto para a tipografia electrónica, mantendo-se essencialmente inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente com os programas de publicação como o Aldus PageMaker que incluem versões do Lorem Ipsum.",
        inCart: false,
        count: 0,
        total: 0,
    },

];

export const detailProduct = {
    id: 1,
    title: "Google Pixel - Black",
    img: "img/product-1.png",
    price: 10,
    company: "GOOGLE",
    info: "jfkfbvobvb",
    inCart: false,
    count: 0,
    total: 0,

    id: 2,
        title: "Samsung S7",
        img: "img/product-1.jpg",
        price: 16,
        company: "SAMSUNG",
        info: "bcibwioqhcioh",
        inCart: false,
        count: 0,
        total: 0,

    id: 3,
        title: "Samsung S7",
        img: "img/product-1.jpg",
        price: 16,
        company: "SAMSUNG",
        info: "bcibwioqhcioh",
        inCart: false,
        count: 0,
        total: 0,

}